name: Create Build Branch

on:
  create:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !endsWith( github.event.ref, '-build') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Build Branch
        run: |
          export UNPARSED_BRANCH=${{ github.event.ref }}
          export BRANCH=${UNPARSED_BRANCH#refs/heads/}
          git checkout $BRANCH
          git pull
          git checkout -b ${BRANCH}-build
          git push -u origin ${BRANCH}-build
