name: Create Build Branch

on:
  create:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !endsWith( github.ref, '-build') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        if: ${{ !endsWith( github.ref, '-build') }}
        run: |
          export BRANCH=${GITHUB_REF#refs/heads/}-build
          git checkout -b $BRANCH
          git push -u origin $BRANCH
