name: Create Build Branch

on:
  create:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !endsWith( github.event.ref, '-build') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Build Branch
        run: |
          if [ "${{ github.event.ref }}" == "refs/heads/"* ]
          then
            export BRANCH=${${{ github.event.ref }}#refs/heads/}-build
            echo "Stripping prefix: $BRANCH"
          else
            export BRANCH=${{ github.event.ref }}-build
            echo "No prefix: $BRANCH"
          fi

          git checkout -b $BRANCH
          git push -u origin $BRANCH
