name: Create Build Branch

on:
  create:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !endsWith( github.event.ref, '-build') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create Build Branch
        run: |
          export BRANCH=${${{ github.event.ref }}#refs/heads/}-build
          git checkout -b $BRANCH
          git push -u origin $BRANCH
