# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    if: ${{ !endsWith( github.event.ref, '-build') }}
    runs-on: ubuntu-latest

    steps:
    
      - name: Wait 30 seconds to allow for the branch to be created if new
        run: sleep 30
        shell: bash
        
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Checkout build branch, merge in any changes and push
        run: |
          export UNPARSED_BRANCH=${{ github.event.ref }}
          export PARSED_BRANCH=${UNPARSED_BRANCH#refs/heads/}
          export BUILD_BRANCH=${PARSED_BRANCH}-build
          git checkout $BUILD_BRANCH
          git merge $PARSED_BRANCH
          git push -u origin $BUILD_BRANCH
        
      - name: Yarn install and build
        run: |
          yarn install
          yarn build
          
      - name: Add build output and commit
        run: |
          export UNPARSED_BRANCH=${{ github.event.ref }}
          export PARSED_BRANCH=${UNPARSED_BRANCH#refs/heads/}
          export BUILD_BRANCH=${PARSED_BRANCH}-build
          git checkout $BUILD_BRANCH
          git add -f build/**
          git commit -m "Commit build artifacts"
          git push -u origin $BUILD_BRANCH
        
      #- name: Commit build artifacts
      #  uses: EndBug/add-and-commit@v7
      #  with:
      #    author_name: github-actions
      #    author_email: 41898282+github-actions[bot]@users.noreply.github.com
      #    message: 'Commit build artifacts'
      #    push: origin "${GITHUB_REF#refs/heads/}-build"
      #    add: -f 'build/**'
